### ISSUE TITLE
deposit dai gives error that approve() needs to be called first

### ISSUE THREAD

**Issue by AdrianScott** [critesjosh/azteccli#1]
azteccli deposit 2.5 --asset dai --time instant
Setting up the SDK... done
Awaiting user signature... done
    Error: Insufficient allowance. Call approve() first.

**Comment by critesjosh** [comment]
This is fixed in the main branch of the repo, it still doesn't work with the latest published npm version. 

To use the latest build that is the most bug free run the tool building from source, https://docs.aztec.network/developers/cli#compile-from-source

I'll publish a new version to npm right now so this isn't an error, but during development it is nice to build from source so you can make modifications and test them instantly as well.
